### ISSUE TITLE
Hardware info flag user readable

### ISSUE THREAD

**Issue by vj396** [michaeljs1990/collins-go-cli#27]
It would be nice to have the flags for hardware info, to spit results out in human readable format.

right now, when we run a query asking for hw info, like `collins find <some param> -x disk_storage_total`, the column for `disk_storage_total` is in bytes, it would be nice to have that in human readable format like, X-KB or X-Gb/GB.

along with that, it would be nice to know the what type of drive it is, say, a micron-ssd, samsung etc.
with a flag/attr call like `disk_storage_type`?

**Comment by michaeljs1990** [comment]
```
1428850 (HEAD -> master, origin/master) Better output for disk_types
5ea9b71 Add support for disk type
b9dc13c Add disk_storage_human
3e31c4e Helper function for bytes -> human
```

The following commits add support for this under the `disk_storage_human` and `disk_types` fields.

here is an example.
```
user@rice ~/code/collins-go-cli $ ./collins query -t M0000001 -x disk_storage_human,disk_types
M0000001        plex-8316f3de71.pit1.terame.com plexnode        Allocated       PRODUCTION      PLEX            136.13 GB       DELL PERC 6/i,TSSTcorp DVD-ROM TS-L333A
```
