### ISSUE TITLE
Client doesn't appear to support mixed case powerOff command

### ISSUE THREAD

**Issue by Cull-Methi** [michaeljs1990/collins-go-cli#45]
```
collins power -t U007104 -p powerOff     
```

Works in the ruby client. When trying to run it in the go client it yields:

```
Unknown power action rebootx, expecting one of reboot,rebootsoft,reboothard,on,off,poweron,poweroff,identify,verify 
```

Can fix that here https://github.com/michaeljs1990/collins-go-cli/blob/f050c57e374c26e3ea988612e127ca99d5673173/collins/commands/power.go#L68

By either adding `"powerOff"` as a possibility or making the whole switch statement case insensitive

**Comment by michaeljs1990** [comment]
Fixed in ca4897b8d53de2c0989b36330c0b42a70b6507fd
