### ISSUE TITLE
Collins find with attribute does not print the queried attrs

### ISSUE THREAD

**Issue by vj396** [michaeljs1990/collins-go-cli#5]
Historically, when we queried something like `collins find -a attr:attr_value` the output would include the `attr` column.

But, seems like we break this feature in this migration.

**Comment by michaeljs1990** [comment]
Looks like I have two things messed up here. I need to fix what you have listed above and It also only currently looks at the last `-a` flag passed in.

**Comment by michaeljs1990** [comment]
This should be fixed in the latest master. Thanks for the report!
